spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql:5432/jr_hotel}
    username: ${SPRING_DATASOURCE_USERNAME:jr_hotel}
    password: ${SPRING_DATASOURCE_PASSWORD:jr_hotel}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  mail:
    host: ${SPRING_MAIL_HOST:maildev}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
